/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ajout_planatation (void);
GtkWidget* create_afficher_planatation (void);
GtkWidget* create_supprimer_planatation (void);
GtkWidget* create_modifier_planatation (void);
GtkWidget* create_annee_plus_seche (void);
GtkWidget* create_chercher_planatation (void);
GtkWidget* create_gestion_planatation (void);
