/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ajout_planatation (void)
{
  GtkWidget *ajout_planatation;
  GtkWidget *fixed1;
  GtkWidget *type;
  GtkWidget *quantite;
  GtkObject *jour_adj;
  GtkWidget *jour;
  GtkObject *mois_adj;
  GtkWidget *mois;
  GtkWidget *label2;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkObject *annee_adj;
  GtkWidget *annee;
  GtkWidget *label14;
  GtkWidget *label3;
  GtkWidget *label1;
  GtkWidget *button1;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label4;
  GtkWidget *annuler;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label25;

  ajout_planatation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ajout_planatation, 494, 314);
  gtk_window_set_title (GTK_WINDOW (ajout_planatation), _("ajouter un planatation"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (ajout_planatation), fixed1);
  gtk_widget_set_size_request (fixed1, 412, 272);

  type = gtk_entry_new ();
  gtk_widget_show (type);
  gtk_fixed_put (GTK_FIXED (fixed1), type, 136, 64);
  gtk_widget_set_size_request (type, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (type), 8226);

  quantite = gtk_entry_new ();
  gtk_widget_show (quantite);
  gtk_fixed_put (GTK_FIXED (fixed1), quantite, 136, 160);
  gtk_widget_set_size_request (quantite, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (quantite), 8226);

  jour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour = gtk_spin_button_new (GTK_ADJUSTMENT (jour_adj), 1, 0);
  gtk_widget_show (jour);
  gtk_fixed_put (GTK_FIXED (fixed1), jour, 112, 112);
  gtk_widget_set_size_request (jour, 60, 27);

  mois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois = gtk_spin_button_new (GTK_ADJUSTMENT (mois_adj), 1, 0);
  gtk_widget_show (mois);
  gtk_fixed_put (GTK_FIXED (fixed1), mois, 232, 112);
  gtk_widget_set_size_request (mois, 60, 27);

  label2 = gtk_label_new (_("saison :"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 0, 112);
  gtk_widget_set_size_request (label2, 72, 25);

  label12 = gtk_label_new (_("jour :"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed1), label12, 64, 112);
  gtk_widget_set_size_request (label12, 56, 24);

  label13 = gtk_label_new (_("mois : "));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed1), label13, 176, 112);
  gtk_widget_set_size_request (label13, 64, 24);

  annee_adj = gtk_adjustment_new (2017, 2017, 2020, 1, 10, 10);
  annee = gtk_spin_button_new (GTK_ADJUSTMENT (annee_adj), 1, 0);
  gtk_widget_show (annee);
  gtk_fixed_put (GTK_FIXED (fixed1), annee, 352, 112);
  gtk_widget_set_size_request (annee, 60, 27);
  gtk_spin_button_set_snap_to_ticks (GTK_SPIN_BUTTON (annee), TRUE);

  label14 = gtk_label_new (_("annee :"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed1), label14, 288, 112);
  gtk_widget_set_size_request (label14, 64, 24);

  label3 = gtk_label_new (_("quantite :"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 0, 152);
  gtk_widget_set_size_request (label3, 120, 48);

  label1 = gtk_label_new (_("type :"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 0, 72);
  gtk_widget_set_size_request (label1, 80, 24);

  button1 = gtk_button_new ();
  gtk_widget_show (button1);
  gtk_fixed_put (GTK_FIXED (fixed1), button1, 152, 232);
  gtk_widget_set_size_request (button1, 112, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button1), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("ajouter "));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox1), label4, FALSE, FALSE, 0);

  annuler = gtk_button_new ();
  gtk_widget_show (annuler);
  gtk_fixed_put (GTK_FIXED (fixed1), annuler, 304, 232);
  gtk_widget_set_size_request (annuler, 88, 32);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (annuler), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("annuler"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox10), label25, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button1, "clicked",
                    G_CALLBACK (on_button1_clicked),
                    NULL);
  g_signal_connect ((gpointer) annuler, "clicked",
                    G_CALLBACK (on_annuler_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ajout_planatation, ajout_planatation, "ajout_planatation");
  GLADE_HOOKUP_OBJECT (ajout_planatation, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (ajout_planatation, type, "type");
  GLADE_HOOKUP_OBJECT (ajout_planatation, quantite, "quantite");
  GLADE_HOOKUP_OBJECT (ajout_planatation, jour, "jour");
  GLADE_HOOKUP_OBJECT (ajout_planatation, mois, "mois");
  GLADE_HOOKUP_OBJECT (ajout_planatation, label2, "label2");
  GLADE_HOOKUP_OBJECT (ajout_planatation, label12, "label12");
  GLADE_HOOKUP_OBJECT (ajout_planatation, label13, "label13");
  GLADE_HOOKUP_OBJECT (ajout_planatation, annee, "annee");
  GLADE_HOOKUP_OBJECT (ajout_planatation, label14, "label14");
  GLADE_HOOKUP_OBJECT (ajout_planatation, label3, "label3");
  GLADE_HOOKUP_OBJECT (ajout_planatation, label1, "label1");
  GLADE_HOOKUP_OBJECT (ajout_planatation, button1, "button1");
  GLADE_HOOKUP_OBJECT (ajout_planatation, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (ajout_planatation, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (ajout_planatation, image1, "image1");
  GLADE_HOOKUP_OBJECT (ajout_planatation, label4, "label4");
  GLADE_HOOKUP_OBJECT (ajout_planatation, annuler, "annuler");
  GLADE_HOOKUP_OBJECT (ajout_planatation, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (ajout_planatation, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (ajout_planatation, image10, "image10");
  GLADE_HOOKUP_OBJECT (ajout_planatation, label25, "label25");

  return ajout_planatation;
}

GtkWidget*
create_afficher_planatation (void)
{
  GtkWidget *afficher_planatation;
  GtkWidget *fixed2;
  GtkWidget *treeview1;

  afficher_planatation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (afficher_planatation, 442, 392);
  gtk_window_set_title (GTK_WINDOW (afficher_planatation), _("affiche d'un planatation"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (afficher_planatation), fixed2);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1, 72, 88);
  gtk_widget_set_size_request (treeview1, 300, 200);

  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (afficher_planatation, afficher_planatation, "afficher_planatation");
  GLADE_HOOKUP_OBJECT (afficher_planatation, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (afficher_planatation, treeview1, "treeview1");

  return afficher_planatation;
}

GtkWidget*
create_supprimer_planatation (void)
{
  GtkWidget *supprimer_planatation;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *fixed3;
  GtkWidget *type2;
  GtkWidget *button2;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label6;
  GtkWidget *label5;

  supprimer_planatation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (supprimer_planatation, 475, 333);
  gtk_window_set_title (GTK_WINDOW (supprimer_planatation), _("supprimer un planatation"));
  gtk_window_set_default_size (GTK_WINDOW (supprimer_planatation), 60, 60);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (supprimer_planatation), scrolledwindow1);
  gtk_widget_set_size_request (scrolledwindow1, 200, 200);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (viewport1), fixed3);
  gtk_widget_set_size_request (fixed3, 411, 77);
  gtk_container_set_border_width (GTK_CONTAINER (fixed3), 29);

  type2 = gtk_entry_new ();
  gtk_widget_show (type2);
  gtk_fixed_put (GTK_FIXED (fixed3), type2, 224, 88);
  gtk_widget_set_size_request (type2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (type2), 8226);

  button2 = gtk_button_new ();
  gtk_widget_show (button2);
  gtk_fixed_put (GTK_FIXED (fixed3), button2, 128, 160);
  gtk_widget_set_size_request (button2, 128, 48);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button2), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox2), label6, FALSE, FALSE, 0);

  label5 = gtk_label_new (_("type :"));
  gtk_widget_show (label5);
  gtk_fixed_put (GTK_FIXED (fixed3), label5, 0, 88);
  gtk_widget_set_size_request (label5, 224, 32);

  g_signal_connect ((gpointer) button2, "clicked",
                    G_CALLBACK (on_button2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (supprimer_planatation, supprimer_planatation, "supprimer_planatation");
  GLADE_HOOKUP_OBJECT (supprimer_planatation, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (supprimer_planatation, viewport1, "viewport1");
  GLADE_HOOKUP_OBJECT (supprimer_planatation, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (supprimer_planatation, type2, "type2");
  GLADE_HOOKUP_OBJECT (supprimer_planatation, button2, "button2");
  GLADE_HOOKUP_OBJECT (supprimer_planatation, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (supprimer_planatation, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (supprimer_planatation, image2, "image2");
  GLADE_HOOKUP_OBJECT (supprimer_planatation, label6, "label6");
  GLADE_HOOKUP_OBJECT (supprimer_planatation, label5, "label5");

  return supprimer_planatation;
}

GtkWidget*
create_modifier_planatation (void)
{
  GtkWidget *modifier_planatation;
  GtkWidget *fixed4;
  GtkWidget *type1;
  GtkWidget *quantite1;
  GtkWidget *label7;
  GtkWidget *label9;
  GtkWidget *button3;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label10;
  GtkWidget *label8;
  GtkWidget *label15;
  GtkObject *jour1_adj;
  GtkWidget *jour1;
  GtkWidget *label16;
  GtkObject *mois1_adj;
  GtkWidget *mois1;
  GtkWidget *label17;
  GtkObject *annee1_adj;
  GtkWidget *annee1;
  GtkWidget *Annuler;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label26;

  modifier_planatation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (modifier_planatation, 672, 285);
  gtk_window_set_title (GTK_WINDOW (modifier_planatation), _("modifier un planatation "));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (modifier_planatation), fixed4);

  type1 = gtk_entry_new ();
  gtk_widget_show (type1);
  gtk_fixed_put (GTK_FIXED (fixed4), type1, 232, 48);
  gtk_widget_set_size_request (type1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (type1), 8226);

  quantite1 = gtk_entry_new ();
  gtk_widget_show (quantite1);
  gtk_fixed_put (GTK_FIXED (fixed4), quantite1, 232, 144);
  gtk_widget_set_size_request (quantite1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (quantite1), 8226);

  label7 = gtk_label_new (_("type de planatation a modifier :"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed4), label7, 0, 48);
  gtk_widget_set_size_request (label7, 224, 32);

  label9 = gtk_label_new (_("nouveau quantite des grains :"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed4), label9, 0, 144);
  gtk_widget_set_size_request (label9, 224, 32);

  button3 = gtk_button_new ();
  gtk_widget_show (button3);
  gtk_fixed_put (GTK_FIXED (fixed4), button3, 112, 192);
  gtk_widget_set_size_request (button3, 168, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button3), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-redo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("modifier "));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox3), label10, FALSE, FALSE, 0);

  label8 = gtk_label_new (_("nouveau saison :"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed4), label8, 0, 96);
  gtk_widget_set_size_request (label8, 160, 32);

  label15 = gtk_label_new (_("jour:"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed4), label15, 136, 104);
  gtk_widget_set_size_request (label15, 64, 24);

  jour1_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  jour1 = gtk_spin_button_new (GTK_ADJUSTMENT (jour1_adj), 1, 0);
  gtk_widget_show (jour1);
  gtk_fixed_put (GTK_FIXED (fixed4), jour1, 192, 104);
  gtk_widget_set_size_request (jour1, 60, 27);

  label16 = gtk_label_new (_("mois : "));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 256, 104);
  gtk_widget_set_size_request (label16, 64, 24);

  mois1_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  mois1 = gtk_spin_button_new (GTK_ADJUSTMENT (mois1_adj), 1, 0);
  gtk_widget_show (mois1);
  gtk_fixed_put (GTK_FIXED (fixed4), mois1, 320, 104);
  gtk_widget_set_size_request (mois1, 60, 27);

  label17 = gtk_label_new (_("annee :"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed4), label17, 408, 104);
  gtk_widget_set_size_request (label17, 48, 24);

  annee1_adj = gtk_adjustment_new (1950, 1950, 2020, 1, 10, 10);
  annee1 = gtk_spin_button_new (GTK_ADJUSTMENT (annee1_adj), 1, 0);
  gtk_widget_show (annee1);
  gtk_fixed_put (GTK_FIXED (fixed4), annee1, 472, 104);
  gtk_widget_set_size_request (annee1, 60, 27);

  Annuler = gtk_button_new ();
  gtk_widget_show (Annuler);
  gtk_fixed_put (GTK_FIXED (fixed4), Annuler, 328, 192);
  gtk_widget_set_size_request (Annuler, 114, 37);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (Annuler), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Annuler"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox11), label26, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button3, "clicked",
                    G_CALLBACK (on_button3_clicked),
                    NULL);
  g_signal_connect ((gpointer) Annuler, "clicked",
                    G_CALLBACK (on_Annuler_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (modifier_planatation, modifier_planatation, "modifier_planatation");
  GLADE_HOOKUP_OBJECT (modifier_planatation, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (modifier_planatation, type1, "type1");
  GLADE_HOOKUP_OBJECT (modifier_planatation, quantite1, "quantite1");
  GLADE_HOOKUP_OBJECT (modifier_planatation, label7, "label7");
  GLADE_HOOKUP_OBJECT (modifier_planatation, label9, "label9");
  GLADE_HOOKUP_OBJECT (modifier_planatation, button3, "button3");
  GLADE_HOOKUP_OBJECT (modifier_planatation, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (modifier_planatation, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (modifier_planatation, image3, "image3");
  GLADE_HOOKUP_OBJECT (modifier_planatation, label10, "label10");
  GLADE_HOOKUP_OBJECT (modifier_planatation, label8, "label8");
  GLADE_HOOKUP_OBJECT (modifier_planatation, label15, "label15");
  GLADE_HOOKUP_OBJECT (modifier_planatation, jour1, "jour1");
  GLADE_HOOKUP_OBJECT (modifier_planatation, label16, "label16");
  GLADE_HOOKUP_OBJECT (modifier_planatation, mois1, "mois1");
  GLADE_HOOKUP_OBJECT (modifier_planatation, label17, "label17");
  GLADE_HOOKUP_OBJECT (modifier_planatation, annee1, "annee1");
  GLADE_HOOKUP_OBJECT (modifier_planatation, Annuler, "Annuler");
  GLADE_HOOKUP_OBJECT (modifier_planatation, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (modifier_planatation, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (modifier_planatation, image11, "image11");
  GLADE_HOOKUP_OBJECT (modifier_planatation, label26, "label26");

  return modifier_planatation;
}

GtkWidget*
create_annee_plus_seche (void)
{
  GtkWidget *annee_plus_seche;
  GtkWidget *fixed5;
  GtkWidget *label11;

  annee_plus_seche = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (annee_plus_seche, 535, 255);
  gtk_window_set_title (GTK_WINDOW (annee_plus_seche), _("l'ann\303\251e la plus s\303\250che"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (annee_plus_seche), fixed5);

  label11 = gtk_label_new (_("l'ann\303\251 la plus s\303\250che est : "));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed5), label11, 96, 72);
  gtk_widget_set_size_request (label11, 192, 48);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (annee_plus_seche, annee_plus_seche, "annee_plus_seche");
  GLADE_HOOKUP_OBJECT (annee_plus_seche, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (annee_plus_seche, label11, "label11");

  return annee_plus_seche;
}

GtkWidget*
create_chercher_planatation (void)
{
  GtkWidget *chercher_planatation;
  GtkWidget *fixed6;
  GtkWidget *entry8;
  GtkWidget *label18;
  GtkWidget *button4;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label19;
  GtkWidget *treeview2;

  chercher_planatation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (chercher_planatation, 595, 413);
  gtk_window_set_title (GTK_WINDOW (chercher_planatation), _("chercher planatation"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (chercher_planatation), fixed6);
  gtk_widget_set_size_request (fixed6, 922, 963);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed6), entry8, 224, 112);
  gtk_widget_set_size_request (entry8, 208, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  label18 = gtk_label_new (_("type de planatation a chercher :"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed6), label18, 0, 104);
  gtk_widget_set_size_request (label18, 216, 48);

  button4 = gtk_button_new ();
  gtk_widget_show (button4);
  gtk_fixed_put (GTK_FIXED (fixed6), button4, 176, 176);
  gtk_widget_set_size_request (button4, 112, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button4), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("chercher "));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox4), label19, FALSE, FALSE, 0);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed6), treeview2, 144, 240);
  gtk_widget_set_size_request (treeview2, 300, 200);

  g_signal_connect ((gpointer) button4, "clicked",
                    G_CALLBACK (on_button4_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview2, "row_activated",
                    G_CALLBACK (on_treeview2_row_activated),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (chercher_planatation, chercher_planatation, "chercher_planatation");
  GLADE_HOOKUP_OBJECT (chercher_planatation, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (chercher_planatation, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (chercher_planatation, label18, "label18");
  GLADE_HOOKUP_OBJECT (chercher_planatation, button4, "button4");
  GLADE_HOOKUP_OBJECT (chercher_planatation, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (chercher_planatation, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (chercher_planatation, image4, "image4");
  GLADE_HOOKUP_OBJECT (chercher_planatation, label19, "label19");
  GLADE_HOOKUP_OBJECT (chercher_planatation, treeview2, "treeview2");

  return chercher_planatation;
}

GtkWidget*
create_gestion_planatation (void)
{
  GtkWidget *gestion_planatation;
  GtkWidget *alignment12;
  GtkWidget *fixed7;
  GtkWidget *eventbox2;
  GtkWidget *button5;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label20;
  GtkWidget *eventbox4;
  GtkWidget *button6;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *eventbox3;
  GtkWidget *label21;
  GtkWidget *eventbox7;
  GtkWidget *button7;
  AtkRelationSet *tmp_relation_set;
  AtkRelationType tmp_relationship;
  AtkRelation *tmp_relation;
  AtkObject *button7_relation_targets[1];
  AtkObject *atko;
  GtkWidget *eventbox1;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label23;
  GtkWidget *eventbox8;
  GtkWidget *button8;
  GtkWidget *eventbox5;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label22;
  GtkWidget *eventbox9;
  GtkWidget *button9;
  GtkWidget *eventbox6;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label24;
  GtkWidget *image12;

  gestion_planatation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (gestion_planatation, 442, 532);
  gtk_window_set_title (GTK_WINDOW (gestion_planatation), _("gestion de planatation"));

  alignment12 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (gestion_planatation), alignment12);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (alignment12), fixed7);

  eventbox2 = gtk_event_box_new ();
  gtk_widget_show (eventbox2);
  gtk_fixed_put (GTK_FIXED (fixed7), eventbox2, 104, 72);
  gtk_widget_set_size_request (eventbox2, 180, 60);

  button5 = gtk_button_new ();
  gtk_widget_show (button5);
  gtk_container_add (GTK_CONTAINER (eventbox2), button5);
  gtk_widget_set_size_request (button5, 180, 60);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button5), alignment5);
  gtk_widget_set_size_request (alignment5, 71, 17);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label20 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label20);
  gtk_box_pack_start (GTK_BOX (hbox5), label20, FALSE, FALSE, 0);

  eventbox4 = gtk_event_box_new ();
  gtk_widget_show (eventbox4);
  gtk_fixed_put (GTK_FIXED (fixed7), eventbox4, 96, 152);
  gtk_widget_set_size_request (eventbox4, 180, 60);

  button6 = gtk_button_new ();
  gtk_widget_show (button6);
  gtk_container_add (GTK_CONTAINER (eventbox4), button6);
  gtk_widget_set_size_request (button6, 180, 60);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button6), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  eventbox3 = gtk_event_box_new ();
  gtk_widget_show (eventbox3);
  gtk_box_pack_start (GTK_BOX (hbox6), eventbox3, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label21);
  gtk_container_add (GTK_CONTAINER (eventbox3), label21);

  eventbox7 = gtk_event_box_new ();
  gtk_widget_show (eventbox7);
  gtk_fixed_put (GTK_FIXED (fixed7), eventbox7, 96, 232);
  gtk_widget_set_size_request (eventbox7, 180, 60);

  button7 = gtk_button_new ();
  gtk_widget_show (button7);
  gtk_container_add (GTK_CONTAINER (eventbox7), button7);
  gtk_widget_set_size_request (button7, 180, 60);

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_container_add (GTK_CONTAINER (button7), eventbox1);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (eventbox1), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("chercher"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox8), label23, FALSE, FALSE, 0);

  eventbox8 = gtk_event_box_new ();
  gtk_widget_show (eventbox8);
  gtk_fixed_put (GTK_FIXED (fixed7), eventbox8, 96, 304);
  gtk_widget_set_size_request (eventbox8, 180, 60);

  button8 = gtk_button_new ();
  gtk_widget_show (button8);
  gtk_container_add (GTK_CONTAINER (eventbox8), button8);
  gtk_widget_set_size_request (button8, 180, 60);

  eventbox5 = gtk_event_box_new ();
  gtk_widget_show (eventbox5);
  gtk_container_add (GTK_CONTAINER (button8), eventbox5);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (eventbox5), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label22 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label22);
  gtk_box_pack_start (GTK_BOX (hbox7), label22, FALSE, FALSE, 0);

  eventbox9 = gtk_event_box_new ();
  gtk_widget_show (eventbox9);
  gtk_fixed_put (GTK_FIXED (fixed7), eventbox9, 96, 384);
  gtk_widget_set_size_request (eventbox9, 180, 60);

  button9 = gtk_button_new ();
  gtk_widget_show (button9);
  gtk_container_add (GTK_CONTAINER (eventbox9), button9);
  gtk_widget_set_size_request (button9, 180, 60);

  eventbox6 = gtk_event_box_new ();
  gtk_widget_show (eventbox6);
  gtk_container_add (GTK_CONTAINER (button9), eventbox6);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (eventbox6), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-goto-first", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox9), label24, FALSE, FALSE, 0);

  image12 = create_pixmap (gestion_planatation, "COVID-19-Relief_Small-Farms-.jpeg");
  gtk_widget_show (image12);
  gtk_fixed_put (GTK_FIXED (fixed7), image12, 0, 0);
  gtk_widget_set_size_request (image12, 448, 544);

  g_signal_connect ((gpointer) button5, "clicked",
                    G_CALLBACK (on_button5_clicked),
                    NULL);
  g_signal_connect ((gpointer) button6, "clicked",
                    G_CALLBACK (on_button6_clicked),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_button7_clicked),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_button8_clicked),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_button9_clicked),
                    NULL);

  atko = gtk_widget_get_accessible (button7);
  tmp_relation_set = atk_object_ref_relation_set (atko);
  button7_relation_targets[0] = gtk_widget_get_accessible (button7);
  tmp_relationship = atk_relation_type_for_name ("subwindow-of");
  tmp_relation = atk_relation_new (button7_relation_targets, 1, tmp_relationship);
  atk_relation_set_add (tmp_relation_set, tmp_relation);
  g_object_unref (G_OBJECT (tmp_relation));
  g_object_unref (G_OBJECT (tmp_relation_set));


  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_planatation, gestion_planatation, "gestion_planatation");
  GLADE_HOOKUP_OBJECT (gestion_planatation, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (gestion_planatation, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (gestion_planatation, eventbox2, "eventbox2");
  GLADE_HOOKUP_OBJECT (gestion_planatation, button5, "button5");
  GLADE_HOOKUP_OBJECT (gestion_planatation, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (gestion_planatation, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (gestion_planatation, image5, "image5");
  GLADE_HOOKUP_OBJECT (gestion_planatation, label20, "label20");
  GLADE_HOOKUP_OBJECT (gestion_planatation, eventbox4, "eventbox4");
  GLADE_HOOKUP_OBJECT (gestion_planatation, button6, "button6");
  GLADE_HOOKUP_OBJECT (gestion_planatation, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (gestion_planatation, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (gestion_planatation, image6, "image6");
  GLADE_HOOKUP_OBJECT (gestion_planatation, eventbox3, "eventbox3");
  GLADE_HOOKUP_OBJECT (gestion_planatation, label21, "label21");
  GLADE_HOOKUP_OBJECT (gestion_planatation, eventbox7, "eventbox7");
  GLADE_HOOKUP_OBJECT (gestion_planatation, button7, "button7");
  GLADE_HOOKUP_OBJECT (gestion_planatation, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (gestion_planatation, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (gestion_planatation, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (gestion_planatation, image8, "image8");
  GLADE_HOOKUP_OBJECT (gestion_planatation, label23, "label23");
  GLADE_HOOKUP_OBJECT (gestion_planatation, eventbox8, "eventbox8");
  GLADE_HOOKUP_OBJECT (gestion_planatation, button8, "button8");
  GLADE_HOOKUP_OBJECT (gestion_planatation, eventbox5, "eventbox5");
  GLADE_HOOKUP_OBJECT (gestion_planatation, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (gestion_planatation, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (gestion_planatation, image7, "image7");
  GLADE_HOOKUP_OBJECT (gestion_planatation, label22, "label22");
  GLADE_HOOKUP_OBJECT (gestion_planatation, eventbox9, "eventbox9");
  GLADE_HOOKUP_OBJECT (gestion_planatation, button9, "button9");
  GLADE_HOOKUP_OBJECT (gestion_planatation, eventbox6, "eventbox6");
  GLADE_HOOKUP_OBJECT (gestion_planatation, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (gestion_planatation, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (gestion_planatation, image9, "image9");
  GLADE_HOOKUP_OBJECT (gestion_planatation, label24, "label24");
  GLADE_HOOKUP_OBJECT (gestion_planatation, image12, "image12");

  gtk_widget_grab_default (image12);
  return gestion_planatation;
}

