/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *ajout_planatation;

  GtkWidget *afficher_planatation;
  GtkWidget *modifier_planatation;
  GtkWidget *supprimer_planatation;
  GtkWidget *anne_plus_seche;
  GtkWidget *chercher_planatation;
  GtkWidget *gestion_planatation ;
  

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
 */
  gestion_planatation = create_gestion_planatation () ;
  gtk_widget_show (gestion_planatation);
  /*ajout_planatation = create_ajout_planatation ();
  gtk_widget_show (ajout_planatation);
  supprimer_planatation = create_supprimer_planatation ();
  gtk_widget_show (supprimer_planatation);
  modifier_planatation = create_modifier_planatation ();
  gtk_widget_show (modifier_planatation);
  chercher_planatation = create_chercher_planatation ();
  gtk_widget_show (chercher_planatation);*/
  
  gtk_main ();
  return 0;
}

